//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ad_vehicule
    {
        public int id_ad_vehicule { get; set; }
        public Nullable<int> id_ad { get; set; }
        public Nullable<int> annee { get; set; }
        public Nullable<int> mileage { get; set; }
        public Nullable<int> id_transmission { get; set; }
        public Nullable<int> id_carburant { get; set; }
        public string marque { get; set; }
        public string modele { get; set; }
    
        public virtual tb_ads tb_ads { get; set; }
    }
}
