//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ad_status
    {
        public tb_ad_status()
        {
            this.tb_ads = new HashSet<tb_ads>();
        }
    
        public int id_ad_status { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<tb_ads> tb_ads { get; set; }
    }
}
