//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ad_image
    {
        public int id_image { get; set; }
        public Nullable<int> id_ad { get; set; }
        public string ad_code { get; set; }
        public string image_filename { get; set; }
        public string image_path { get; set; }
    
        public virtual tb_ads tb_ads { get; set; }
    }
}
