//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ad_immobilier
    {
        public int id_ad_immobilier { get; set; }
        public Nullable<int> id_ad { get; set; }
        public Nullable<int> id_nb_pieces { get; set; }
        public Nullable<int> id_nb_chambre { get; set; }
        public Nullable<int> surface { get; set; }
        public Nullable<double> loyer { get; set; }
    
        public virtual tb_ads tb_ads { get; set; }
    }
}
