//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_account_type
    {
        public tb_account_type()
        {
            this.tb_account = new HashSet<tb_account>();
        }
    
        public int id_account_type { get; set; }
        public string account_type { get; set; }
    
        public virtual ICollection<tb_account> tb_account { get; set; }
    }
}
