//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ad_reference
    {
        public int id_ref { get; set; }
        public string ref_name { get; set; }
        public string ref_item { get; set; }
        public Nullable<int> ref_item_id { get; set; }
        public string ref_input_type { get; set; }
    }
}
