//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_account
    {
        public tb_account()
        {
            this.tb_ads = new HashSet<tb_ads>();
        }
    
        public int id_account { get; set; }
        public Nullable<int> id_account_type { get; set; }
        public Nullable<System.Guid> id_user { get; set; }
        public Nullable<int> UserId { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string username { get; set; }
        public string pseudo { get; set; }
        public string nom_entreprise { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string adresse { get; set; }
        public string role { get; set; }
        public string status { get; set; }
    
        public virtual tb_account_type tb_account_type { get; set; }
        public virtual tb_user_profile tb_user_profile { get; set; }
        public virtual ICollection<tb_ads> tb_ads { get; set; }
    }
}
