//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ads
    {
        public tb_ads()
        {
            this.tb_ad_image = new HashSet<tb_ad_image>();
            this.tb_message = new HashSet<tb_message>();
            this.tb_ad_vehicule = new HashSet<tb_ad_vehicule>();
            this.tb_ad_chaussure = new HashSet<tb_ad_chaussure>();
            this.tb_ad_immobilier = new HashSet<tb_ad_immobilier>();
        }
    
        public int id_ad { get; set; }
        public Nullable<int> id_section { get; set; }
        public Nullable<int> id_category { get; set; }
        public string ad_title { get; set; }
        public string ad_description { get; set; }
        public Nullable<int> ad_status { get; set; }
        public Nullable<int> ad_is_published { get; set; }
        public string ad_name { get; set; }
        public string ad_email { get; set; }
        public string ad_phone { get; set; }
        public Nullable<System.DateTime> ad_date_created { get; set; }
        public Nullable<System.DateTime> ad_date_expired { get; set; }
        public Nullable<int> id_item_condition { get; set; }
        public Nullable<double> ad_price { get; set; }
        public Nullable<int> ad_type { get; set; }
        public Nullable<int> id_commune { get; set; }
        public Nullable<int> id_departement { get; set; }
        public Nullable<int> id_account { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> id_devise { get; set; }
        public Nullable<System.Guid> id_user { get; set; }
        public string ad_code { get; set; }
    
        public virtual tb_account tb_account { get; set; }
        public virtual tb_ad_condition tb_ad_condition { get; set; }
        public virtual ICollection<tb_ad_image> tb_ad_image { get; set; }
        public virtual tb_ad_status tb_ad_status { get; set; }
        public virtual tb_ads_type tb_ads_type { get; set; }
        public virtual tb_category tb_category { get; set; }
        public virtual tb_commune tb_commune { get; set; }
        public virtual tb_departement tb_departement { get; set; }
        public virtual tb_devise tb_devise { get; set; }
        public virtual tb_section tb_section { get; set; }
        public virtual tb_user_profile tb_user_profile { get; set; }
        public virtual ICollection<tb_message> tb_message { get; set; }
        public virtual tb_ads tb_ads1 { get; set; }
        public virtual tb_ads tb_ads2 { get; set; }
        public virtual ICollection<tb_ad_vehicule> tb_ad_vehicule { get; set; }
        public virtual ICollection<tb_ad_chaussure> tb_ad_chaussure { get; set; }
        public virtual ICollection<tb_ad_immobilier> tb_ad_immobilier { get; set; }
    }
}
