//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_category
    {
        public tb_category()
        {
            this.tb_ads = new HashSet<tb_ads>();
        }
    
        public int id_category { get; set; }
        public Nullable<int> id_section { get; set; }
        public string category_title { get; set; }
        public string category_desctiption { get; set; }
        public Nullable<int> category_order { get; set; }
    
        public virtual tb_section tb_section { get; set; }
        public virtual ICollection<tb_ads> tb_ads { get; set; }
    }
}
