//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_devise
    {
        public tb_devise()
        {
            this.tb_ads = new HashSet<tb_ads>();
        }
    
        public int id_devise { get; set; }
        public string description { get; set; }
        public string symbole { get; set; }
    
        public virtual ICollection<tb_ads> tb_ads { get; set; }
    }
}
