//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_section
    {
        public tb_section()
        {
            this.tb_category = new HashSet<tb_category>();
            this.tb_ads = new HashSet<tb_ads>();
        }
    
        public int id_section { get; set; }
        public string section_title { get; set; }
        public string section_description { get; set; }
        public Nullable<int> section_order { get; set; }
        public string icon_image { get; set; }
    
        public virtual ICollection<tb_category> tb_category { get; set; }
        public virtual ICollection<tb_ads> tb_ads { get; set; }
    }
}
