//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user_profile
    {
        public tb_user_profile()
        {
            this.tb_account = new HashSet<tb_account>();
            this.tb_ads = new HashSet<tb_ads>();
        }
    
        public int UserId { get; set; }
        public string username { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<tb_account> tb_account { get; set; }
        public virtual ICollection<tb_ads> tb_ads { get; set; }
    }
}
