//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toutokaz.Domain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class toutokaz_dbEntities : DbContext
    {
        public toutokaz_dbEntities()
            : base("name=toutokaz_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_account_type> tb_account_type { get; set; }
        public DbSet<tb_ad_image> tb_ad_image { get; set; }
        public DbSet<tb_ad_option> tb_ad_option { get; set; }
        public DbSet<tb_ads_type> tb_ads_type { get; set; }
        public DbSet<tb_category> tb_category { get; set; }
        public DbSet<tb_commune> tb_commune { get; set; }
        public DbSet<tb_departement> tb_departement { get; set; }
        public DbSet<tb_devise> tb_devise { get; set; }
        public DbSet<tb_message> tb_message { get; set; }
        public DbSet<tb_section> tb_section { get; set; }
        public DbSet<tb_ad_condition> tb_ad_condition { get; set; }
        public DbSet<tb_ad_status> tb_ad_status { get; set; }
        public DbSet<tb_contact> tb_contact { get; set; }
        public DbSet<tb_account> tb_account { get; set; }
        public DbSet<tb_user_profile> tb_user_profile { get; set; }
        public DbSet<tb_ads> tb_ads { get; set; }
        public DbSet<tb_ad_reference> tb_ad_reference { get; set; }
        public DbSet<tb_ad_vehicule> tb_ad_vehicule { get; set; }
        public DbSet<tb_ad_chaussure> tb_ad_chaussure { get; set; }
        public DbSet<tb_ad_immobilier> tb_ad_immobilier { get; set; }
    }
}
